[workspace]
members = [
  "substrate-archive",
  "substrate-archive-backend",
  "work-queue/sa-work-queue/",
  "work-queue/sa_work_queue_proc_macro/",
  "test-common",
  "test-common/test-wasm"
]

exclude = [
  "bin/polkadot-archive",
  "bin/node-template-archive"
]
