[workspace]
members = [
  "substrate-archive",
  "substrate-archive-backend",
  "work-queue",
  "test-common",
  "test-common/test-wasm"
]

exclude = [
  "bin/polkadot-archive",
  "bin/node-template-archive"
]
