[chain]
# Must be an absolute path to chain data db (no ~/)
# Can also be specified via the `CHAIN_DATA_DB` environment variable
data_path = "/home/insipx/.local/share/node-template/chains/dev/db"

# How much should the read-only database keep in cache (MB)
# Optional, default: 128
cache_size = 128

# Rocksdb secondary directory, output will be `./output/rocksdb_secondary/`
# Optional, default: /<local>/substrate_archive/rocksdb_secondary/
rocksdb_secondary_path = "./output/"

[runtime]
# Specification of different methods of executing the runtime Wasm code.
# Optional, "Interpreted" or "Compiled", default: "Interpreted"
#exec_method = "Interpreted"

# Number of threads to dedicate for executing blocks
# Optional, default: the number of logical system threads
block_workers = 4

# Number of 64KB Heap Pages to allocate for WASM execution
# Optional, default: 64 * the number of logical system threads
wasm_pages = 512

[database]
# Database url.
# Can also be specified via the `DATABASE_URL` environment variable
url = "postgres://user:pass@localhost:5432/archive"

[log]
# Optional log level of stdout, default: "DEBUG"
std = "DEBUG"

# Optional file log.
#[log.file]
# Optional log level of file, default: "DEBUG"
#level = "DEBUG"
# Optional log file directory path, default: "/<local>/substrate_archive/"
#dir = "./output/"
# Optional log file name, default: "archive.log"
#name = "archive.log"

[control]
# Number of threads to dedicate for executing tasks
# Optional, default: the number of logical system threads
task_workers = 8

# Maximium number of blocks to load and insert into database at a time.
# Useful for controlling memory usage.
# Optional, defaults: 100,000.
max_block_load = 100000

[wasm_tracing]
# Targets for tracing.
targets = '''wasm_tracing,pallet,frame,state'''

# Folder where tracing-enabled WASM binaries are kept.
#folder = ""
